=== code-and-debug/internship-showcase/03-Source-Code/examples/config-center-demo/config/schemas/tenant.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Tenant Configuration Schema",
  "description": "医院基础配置校验 Schema",
  "type": "object",
  "required": ["sysCode", "name"],
  "properties": {
    "sysCode": {
      "type": "string",
      "description": "医院系统编码"
    },
    "name": {
      "type": "string",
      "description": "医院名称"
    },
    "wxAppid": {
      "type": "string",
      "description": "微信小程序 AppID"
    },
    "alipayAppid": {
      "type": "string",
      "description": "支付宝小程序 AppID"
    },
    "isvAlipayAppid": {
      "type": "string",
      "description": "ISV 支付宝小程序 AppID"
    },
    "h5Appid": {
      "type": "string",
      "description": "H5 微信 AppID"
    },
    "toutiaoAppid": {
      "type": "string",
      "description": "抖音小程序 AppID"
    },
    "harmonyBundleName": {
      "type": "string",
      "description": "鸿蒙 Bundle Name"
    },
    "isSearchInHos": {
      "type": "boolean",
      "description": "是否支持院内搜索"
    },
    "isOpenOcr": {
      "type": "boolean",
      "description": "是否开启 OCR"
    },
    "isOpenHealthCard": {
      "type": "object",
      "description": "健康卡配置"
    },
    "sConfig": {
      "type": "object",
      "description": "业务功能开关配置"
    },
    "_meta": {
      "type": "object",
      "properties": {
        "version": { "type": "string" },
        "createdAt": { "type": "string" },
        "updatedAt": { "type": "string" }
      }
    }
  }
}

=== code-and-debug/internship-showcase/03-Source-Code/examples/config-center-demo/config/tenants/1001033.json
{
  "_meta": {
    "version": "1.0.0",
    "createdAt": "2024-01-15T08:00:00Z",
    "updatedAt": "2024-03-19T10:30:00Z",
    "description": "台州市第一人民医院 - 基础配置"
  },
  "sysCode": "1001033",
  "name": "台州市第一人民医院",
  "wxAppid": "wxe26143481567cb97",
  "alipayAppid": "2021002139602458",
  "isvAlipayAppid": "2021003154665105",
  "h5Appid": "wx8e5a08ccb011d26c",
  "isSearchInHos": true,
  "isOpenOcr": true,
  "sConfig": {
    "isOpenAlipayZndz": true,
    "isDrugDelivery": "1",
    "isOpenHelpOld": "1",
    "isOpenWechatSI": true,
    "medicalMHelp": {
      "wx": {
        "crossProgramBizType": { "clinic": "iAZhaFg90P" },
        "medicalPlugin": "1"
      },
      "alipay": {
        "medicalPlugin": {
          "orgId": { "1279": "H33100300340", "1281": "H3310030034020" },
          "cardType": "01"
        },
        "medicalFiling": "1",
        "isFamilyPayment": "1"
      }
    }
  }
}

=== code-and-debug/internship-showcase/03-Source-Code/examples/config-center-demo/config/tenants/1001035.json
{
  "_meta": {
    "version": "1.2.0",
    "createdAt": "2024-01-15T08:00:00Z",
    "updatedAt": "2024-03-19T10:30:00Z",
    "description": "江苏省中医院 - 基础配置"
  },
  "sysCode": "1001035",
  "name": "江苏省中医院",
  "wxAppid": "wxacb96ee66c3dee84",
  "h5Appid": "wxa5cb8c1829e5603e",
  "alipayAppid": "2021003104670597",
  "isvAlipayAppid": "2021003104670597",
  "toutiaoAppid": "tt00a7761a9facebee01",
  "harmonyBundleName": "com.atomicservice.6917564602329951506",
  "isOpenOcr": false,
  "isSearchInHos": true,
  "sConfig": {
    "homeNavTitleLogo": "https://phsdevoss.eheren.com/pcloud/phs3.0/jiangsushengzhonnavtitle.png",
    "isOpenMessageAuth": "1",
    "isMessageBtnShowNew": "1",
    "isOpenPopularSci": { "wx": "1" },
    "isOpenWechatSI": true,
    "isOpenHelpOld": "1",
    "homeTopBanner": { "topShow": true },
    "medicalMHelp": {
      "wx": {
        "isMedicalOrder": "1",
        "isGbFamilyPayment": "1",
        "medical1001035": {
          "auth": {
            "appId": "wxfde9fffbfa82be54",
            "path": "pages/allOutPayCashier/authUniPro/authUni",
            "extraData": { "appid": "96391c9afe2c46b3bba52436351dd418" }
          },
          "pay": {
            "appId": "wxfde9fffbfa82be54",
            "path": "pages/allOutPayCashier/cashierUniPro/cashierUni",
            "extraData": {
              "appid": "96391c9afe2c46b3bba52436351dd418",
              "channel_code": "b756bf71948144f993bcc768fe7b0910",
              "fixmedinsCode": "H32010400468",
              "fixmedinsName": "江苏省中医院"
            }
          }
        }
      }
    }
  }
}

=== code-and-debug/internship-showcase/examples/config-center/config/tenants/1001033.json
{
  "_meta": {
    "sysCode": "1001033",
    "name": "台州市第一人民医院",
    "createdAt": "2024-01-01",
    "updatedAt": "2024-03-15",
    "version": "1.0.0"
  },
  "sysCode": "1001033",
  "name": "台州市第一人民医院",
  "wxAppid": "wxe26143481567cb97",
  "alipayAppid": "2021002139602458",
  "isSearchInHos": true,
  "isOpenOcr": true,
  "sConfig": {
    "homeNavTitleLogo": "https://cdn.eheren.com/logo/1001033.png",
    "homeTopBanner": {
      "topShow": true,
      "bannerHeight": 200
    },
    "isHideHomeLogo": "0",
    "isDrugDelivery": "1",
    "isOpenHelpOld": "1",
    "isOpenWechatSI": true,
    "thirdPartyService": {
      "pluginId": "PLUGIN_1001033",
      "orgId": {
        "10001": "H000033"
      }
    }
  }
}

=== code-and-debug/internship-showcase/examples/config-center/config/tenants/1001035.json
{
  "_meta": {
    "sysCode": "1001035",
    "name": "玉环市第二人民医院",
    "createdAt": "2024-01-15",
    "updatedAt": "2024-03-10",
    "version": "1.0.0"
  },
  "sysCode": "1001035",
  "name": "玉环市第二人民医院",
  "wxAppid": "wx718cec315197969f",
  "isSearchInHos": false,
  "isOpenOcr": true,
  "sConfig": {
    "homeTopBanner": {
      "topShow": false
    },
    "isHideHomeLogo": "1",
    "isDrugDelivery": "0",
    "isOpenHelpOld": "1",
    "thirdPartyService": {
      "pluginId": "PLUGIN_1001035"
    }
  }
}

=== code-and-debug/internship-showcase/03-Source-Code/examples/config-center-demo/config/tenants/1001046.json
{
  "_meta": {
    "version": "1.1.0",
    "createdAt": "2024-01-15T08:00:00Z",
    "updatedAt": "2024-03-19T10:30:00Z",
    "description": "绍兴市人民医院 - 基础配置"
  },
  "sysCode": "1001046",
  "name": "绍兴市人民医院",
  "wxAppid": "wxb00075173e764492",
  "alipayAppid": "2021003113623396",
  "isvAlipayAppid": "2021003116641812",
  "h5Appid": "wx1be541208ab16799",
  "isSearchInHos": true,
  "isOpenOcr": true,
  "sConfig": {
    "isOpenWechatSI": true,
    "isOpenHomeTabBarMessageBtn": "1",
    "login": { "isAliAuthBase": "1" },
    "medicalMHelp": {
      "isOpenPatToMedicalPat": {},
      "wx": {
        "crossProgramBizType": { "clinic": "6f8FEzfB6q" },
        "medicalPlugin": "1"
      },
      "alipay": {
        "medicalPlugin": {
          "orgId": { "12930": "H33060200131", "13178": "H3306020013120" },
          "appId": { "13178": "20" },
          "cardType": "01"
        },
        "medicalFiling": "1"
      }
    },
    "isOpenHelpOld": "1"
  }
}

=== code-and-debug/internship-showcase/03-Source-Code/examples/config-center-demo/config/tenants/1001093.json
{
  "_meta": {
    "version": "2.0.0",
    "createdAt": "2024-01-15T08:00:00Z",
    "updatedAt": "2024-03-19T10:30:00Z",
    "description": "浙江省肿瘤医院 - 基础配置"
  },
  "sysCode": "1001093",
  "name": "浙江省肿瘤医院",
  "wxAppid": "wx2e06292a91e9f162",
  "alipayAppid": "2021003104628364",
  "h5Appid": "wx425067e6f6726598",
  "isvAlipayAppid": "",
  "isOpenOcr": false,
  "isSearchInHos": true,
  "sConfig": {
    "homeStyle": "1",
    "isOpenHelpOld": "1",
    "login": { "isAliAuthBase": "1", "isSkipPerfect": "1" },
    "isOpenWechatSI": true,
    "isWxShowToggleEcZh": "1",
    "homeTopBanner": { "topShow": true, "bannerHeight": 230 },
    "medicalMHelp": {
      "wx": {
        "medicalPlugin": "1",
        "medicalFiling": "1",
        "crossProgramBizType": {
          "clinic": "T2loeEEdAO",
          "medicalFiling": "Xeu2ztYzX9"
        }
      },
      "alipay": {
        "medicalDefault": "1",
        "medicalFiling": "1",
        "isFamilyPayment": "1",
        "medicalPlugin": { "orgId": { "13152": "H33010500310" }, "cardType": "01" }
      }
    },
    "homeTopBg": "https://phsdevoss.eheren.com/pcloud/phs3.0/stand3-1001093-home-topbg.png",
    "homeNavTitleLogo": "https://phsdevoss.eheren.com/pcloud/phs3.0/stand3-1001093-home-navtitle.png"
  }
}
